### ISSUE TITLE
Node became a zombie after haredis lost connection with DNS 

### ISSUE THREAD

**Issue by shumkov** [carlos8f/haredis#5]
My node service doesn't work properly after DNS service was down.

Into the service log i'm see a warnings from all my redis connections:

```
[23:44:09](haredis#4) warning: Error: getaddrinfo EADDRINFO
```

Service was running, but not responding propertly and looks like a zombie :).

The best approach is try to restart node process a few times.

How can i catch this error?

**Comment by carlos8f** [comment]
Weird that the underlying node_redis client didn't reconnect like it's supposed to, but you uncovered a bug anyway: there was no way to catch errors from individual nodes' node_redis clients. I fixed and published this in v0.2.9, once you are listening for `client.on('error', function...)` the error will get passed to you instead of writing to stderr. Thanks for using haredis!
